### ISSUE TITLE
Help required with non-working Common.SortOrder annotation

### ISSUE THREAD

**Issue by ChristopheGENARD** [SAP/odata-vocabularies#123]
Hello,
I'm currently working on SAP Price Calculation product. 
I would like to have some help with an issue i have when using sorting (common.sortOrder annotation).

For the context, we have an object called "PricingSchemes" with a service "PricingSchemeService".
The annotation for this service is this one : 

**service.cds**

```
annotate PricingSchemeService.PricingSchemes with @(
  UI: {
    DeleteHidden : true,
	  SelectionFields: [ code, name ],
		LineItem: [
		  {Value: code, Label: '{i18n>Code}'},
		  {Value: name, Label: '{i18n>Name}'},
	      {Value: description, Label: '{i18n>Description}'},
		  {Value: description, Label: 'Test'},
          {
            $Type : 'UI.DataFieldForAction',
            Label : '{i18n>Copy}',
            Action : 'PricingSchemeService.draftCopy',
            ![@UI.Importance] : #High
          }
		],
    Identification: [
      {
        Value: code,
        Label:  '{i18n>Code}'
      },
      {
        $Type : 'UI.DataFieldForAction',
        Label : '{i18n>Copy}',
        Action : 'PricingSchemeService.draftCopy',
        ![@UI.Importance] : #High
      }
    ],
    HeaderInfo         : {
        TypeName       : '{i18n>PricingScheme}',
        TypeNamePlural : '{i18n>PricingSchemes}',
        Title          : { Value : code, Label: '{i18n>Code}' },
        Description    : { Value : name, Label: '{i18n>Name}' }
    },
    HeaderFacets:[
      {
          $Type  : 'UI.ReferenceFacet',
          Target : '@UI.FieldGroup#HeaderFacets'
      }
    ],
    Facets: [
        {$Type: 'UI.ReferenceFacet', Label: '{i18n>PricingSchemeItemsList}', Target: 'items/@UI.LineItem'},
        {$Type  : 'UI.ReferenceFacet', Label  : '{i18n>AdministrativeData}', Target : '@UI.FieldGroup#PricingSchemeAdministrativeData'}
    ],
    FieldGroup#HeaderFacets : {
        Data : [
            {Value : description, Label : '{i18n>Description}'}
        ]
    },
    FieldGroup#PricingSchemeAdministrativeData : {Data : [
        {
            Value : createdAt,
            Label : '{i18n>createdAt}'
        },
        {
            Value : createdBy,
            Label : '{i18n>createdBy}'
        },
        {
            Value : modifiedAt,
            Label : '{i18n>modifiedAt}'
        },
        {
            Value : modifiedBy,
            Label : '{i18n>modifiedBy}'
        },
    ]},
	}
);
``` 

This is actually using the default sorting (by ID, asc) while we would like to define or own sorting. 
I've first be using "UI.PresentationVariant" annotation and it works well.

```
UI.PresentationVariant : {
    Visualizations : [
        '@UI.LineItem'
    ],
    RequestAtLeast : [
       code
    ],
    SortOrder : [
        {
            Property : code,
            Descending : false
        }
    ]
  }
```

However, the sorting is only done on the frontend requests, while we would prefer it to be generalize to all API call. (For example, i've been reproducing the correct API call using Postman, and it doesn't apply the sorting)

I've then found this page : https://github.com/SAP/odata-vocabularies/blob/main/vocabularies/Common.md 

NOTE : At this point, PresentationVariant is no longer in the UI annotation.

So, now, I've been trying to add the Common.SortOrder annotation I found in this documentation. By adding this piece of code into the annotation block: 

```
Common: {
    SortOrder: [
      {
        Property: code,
        Descending: false
      }
    ]
  },
  UI: {...}
```

With this, I can build my project (so I guess its not a syntax problem) and push it to my MTX database (using Cloud Foundry `cf push`)  without any problem. 

But when I launch my backend, there isn't any sorting (neither on the UI nor on Postman calls). It's using the default sort (by ID, asc). 

Thank you for your time,
Christophe GENARD

**Comment by ralfhandl** [comment]
@ChristopheGENARD Hi Christophe,

Your problem seems to be that an application (CAP) does not implement `Common.SortOrder`.

Please open an issue with that application.

This repository is only _defining_ the _structure_ of annotations, independent of any applications that fully or partially implement these annotations.

Thanks
Ralf
