### ISSUE TITLE
Type for some terms is DataFieldAbstract rather than DataField

### ISSUE THREAD

**Issue by qmacro** [SAP/odata-vocabularies#190]
In staring at the types for the terms in this vocabulary, I am looking at the `Identification` and `LineItem` terms, both of which are defined as collections of [DataFieldAbstract](https://github.com/SAP/odata-vocabularies/blob/main/vocabularies/UI.md#DataFieldAbstract) types. 

In defining OData annotations for consumption in Fiori Elements and other smart controls, these terms are often used, and often only with the `Value` property, which belongs to the concrete [DataField](https://github.com/SAP/odata-vocabularies/blob/main/vocabularies/UI.md#DataField) type that inherits `Label`, `Criticality`, `CriticalityRepresentation` and `IconUrl` from `DataFieldAbstract`, and which adds that `Value` property.

Here's [an example](https://github.com/SAP-samples/odata-basics-handsonsapdev/blob/c4f95e7e16acf0d21a78a85362ad547c6a2984eb/bookshop/srv/index.cds#L3-L21):

```cds
annotate CatalogService.Books with @(
    UI: {
        Identification: [ {Value: title} ],
        SelectionFields: [ title ],
        LineItem: [
            {Value: ID},
            {Value: title},
            {Value: author.name},
            {Value: author_ID},
            {Value: stock}
        ],
        HeaderInfo: {
            TypeName: '{i18n>Book}',
            TypeNamePlural: '{i18n>Books}',
            Title: {Value: title},
            Description: {Value: author.name}
        }
    }
);
```

The `Identification` term [is defined as](https://github.com/SAP/odata-vocabularies/blob/main/vocabularies/UI.xml#L109) a collection of the `DataFieldAbstract` type which doesn't have the `Value` property. 

```xml
<Term Name="Identification" Type="Collection(UI.DataFieldAbstract)" Nullable="false" AppliesTo="EntityType">
  <Annotation Term="UI.ThingPerspective" />
  <Annotation Term="Core.Description" String="Collection of fields identifying the object" />
</Term>
```

Is it not more appropriate (accurate?) to define it (and `LineItem`, and possibly others) to be of type `Collection(UI.DataField)` instead?

**Comment by BerSie** [comment]
By restricting the definition to UI.DataField we would miss all to the UI.DataFieldFor... annotations, such as DataFieldForAction (it has an action defined instead of a value) or DataFieldForAnnotation (the visualized value comes the annotation that's used in the datafield, e.g. DataPoint).
