### ISSUE TITLE
Allow PropertyPath and String for SemanticObjectProperty attribute of SemanticObjectMappingType

### ISSUE THREAD

**Issue by gregorwolf** [SAP/odata-vocabularies#267]
Hello SAP OData Vocabularies Team,

our Fiori Elements application lists the messages sent for different business objects. In this example for Sales Orders and also Purchase Orders:

Semantic Object | Action | DocumentID | Semantic Object Property
-- | -- | -- | --
SalesOrder | manage | 10004711 | SalesOrder
PurchaseOrder | manage | 55004533 | PurchaseOrder

The requirement is to allow navigation to the original Objects. But the ID field of the target is not DocumentID but SalesOrder or PurchaseOrder. To achieve a working navigation to the Object Page of the target business object I try to use the Mapping attribute of the [DataFieldForIntentBasedNavigation](https://sap.github.io/odata-vocabularies/vocabularies/UI.html#DataFieldForIntentBasedNavigation). That works fine for one business object. But unfortunately the SemanticObjectProperty attribute of [SemanticObjectMappingType](https://sap.github.io/odata-vocabularies/vocabularies/Common.html#SemanticObjectMappingType) is only defined as a String. For my use case I need to fill it dynamically from the column "Semantic Object Property" of the above sample table. I hope that the last resort isn't [DataFieldWithUrl](https://sap.github.io/odata-vocabularies/vocabularies/UI.html#DataFieldWithUrl).

Best Regards
Gregor

**Comment by BerSie** [comment]
Hello Gregor,
re-reading your issue, I recognized that your case is about the SemanticObjectMapping (and not wrt SemanticObject property of the DataFieldForIntentBasedNavigation). In general my remark above stays the same - from the vocabulary point of view you can use a property there that resolves to a string. But wrt Fiori Elements I'm sure that it's not supported yet. I will enhance a backlog item on FE side that's about using Path expressions in IBN DataFields with your requirement.
Best regards,
Bernhard

**Comment by gregorwolf** [comment]
Thank you @BerSie. Will close this issue as the Vocabulary is OK.

**Comment by D033684** [comment]
Hi @BerSie , could you please check backlog item on FE side whats the current status ? Any hope that this will come soon ? 
You can also text me SAP internal, we would need this feature. 
Thanks Michael

**Comment by D033684** [comment]
backlog item on FE side seems solved, I am using this with a use case now. It's working fine. Great Stuff!!
