### ISSUE TITLE
how do we enable oData $expand queries on list page

### ISSUE THREAD

**Issue by shankarigr** [SAP/odata-vocabularies#55]
Hi,

We have a scenario, which uses CAP and UI annotations for UI.
We have two entities
  entity Risks : managed {
 .....
    bp          : Association to BusinessPartners;

  }
using {  API_BUSINESS_PARTNER as external } from '../srv/external/API_BUSINESS_PARTNER.csn';
  entity BusinessPartners as projection on external.A_BusinessPartner {
    key BusinessPartner,
    LastName,
    FirstName
  }

where API_Business_Partner connects to S4HANA onpremise system.

For the UI we are using a list page, where it should display LastName.
In this case, $expand works properly if the data is in csv and the moment I connect to S4HANA system it return null for bp.

Please do help us with it, in case if we are missing something.

Thanks and Regards,
Shankari G R

**Comment by ralfhandl** [comment]
Hi Shankari, 

This question is related to CAP, so please head over here for an answer: https://answers.sap.com/tags/9f13aee1-834c-4105-8e43-ee442775e5ce.

Thanks!
Ralf
