### ISSUE TITLE
No deprecation texts for complex types in markdown

### ISSUE THREAD

**Issue by HeikoTheissen** [SAP/odata-vocabularies#92]
The section for a deprecated complex type in the [markdown file](https://github.com/oasis-tcs/odata-vocabularies/blob/ec6576ed0202f50caaa8e9140893f3c43f4c4565/vocabularies/Org.OData.Aggregation.V1.md#navigationpropertyaggregationcapabilities-navigationpropertyrestriction-deprecated) contains the word "Deprecated", but the [deprecation text](https://github.com/oasis-tcs/odata-vocabularies/blob/ec6576ed0202f50caaa8e9140893f3c43f4c4565/vocabularies/Org.OData.Aggregation.V1.xml#L259-L267) is not shown.

Deprecation texts for terms and properties _are_ shown.

**Comment by ralfhandl** [comment]
Can you point me to an example?

**Comment by HeikoTheissen** [comment]
> Can you point me to an example of a deprecated complex type?

Click on the links above (they are from oasis-tcs/odata-vocabularies#101).

**Comment by ralfhandl** [comment]
This issue is in the wrong repo.

Will be fixed with https://github.com/oasis-tcs/odata-vocabularies/pull/101
